// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_chirps.sql

package database

import (
	"context"
)

const getAllChirps = `-- name: GetAllChirps :exec
SELECT body FROM chirps ORDER BY created_at ASC
`

func (q *Queries) GetAllChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, getAllChirps)
	return err
}
